[proton2]
type = protondrive
username = alex.p.ashworth
password = mVaMmEnoJ8JSXkTebMGoliqyVGvOSxHwqCXA_wRmUmJE37wGz7qTcxvDWCtxqyib
2fa = 937141
client_uid = kvtaf4r3ewhtbunxg33gbcorsw25t3qu
client_access_token = k6qnn5la5h4dhddg4nugocmbeoizbo44
client_refresh_token = erj3ttdtx2qzb4w4gdx6kagtedaohnsx
client_salted_key_pass = aEpnOHIycEoxMzlINmRxaXpwek95V1QwdkVHdHNTMg==

[nextcloud]
type = webdav
url = https://ashworth-cloud.duckdns.org/remote.php/dav/files/ashworth/
vendor = nextcloud
user = ashworth
pass = YYoZwA1ErbwFLeKAwj3hva9Lf-O_xRMMJ4YHhhN4kOCobn4Z

