server {
    listen 80;
    server_name uptime.alex-ashworth.com;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name uptime.alex-ashworth.com;

    ssl_certificate /etc/letsencrypt/live/uptime.alex-ashworth.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/uptime.alex-ashworth.com/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    allow 100.64.0.0/10;
    allow 172.18.0.0/16;
    deny all;

    location / {
        proxy_pass http://uptime-kuma:3001;
        include /etc/nginx/snippets/proxy-common.conf;
        include /etc/nginx/snippets/proxy-websocket.conf;
    }
}
