server {
    listen 80;
    server_name cloud.alex-ashworth.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name cloud.alex-ashworth.com;
    client_max_body_size 50G;
    ssl_certificate /etc/letsencrypt/live/cloud.alex-ashworth.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloud.alex-ashworth.com/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/tailscale-docker-only.conf;

    location = /.well-known/carddav {
        return 301 /remote.php/dav/;
    }

    location = /.well-known/caldav {
        return 301 /remote.php/dav/;
    }

    location / {
        proxy_pass http://nextcloud-app:80;
        include /etc/nginx/snippets/proxy-common.conf;
    }
}
