server {
    listen 80;
    server_name gitea.alex-ashworth.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name gitea.alex-ashworth.com;

    ssl_certificate /etc/letsencrypt/live/gitea.alex-ashworth.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gitea.alex-ashworth.com/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    location / {
        client_max_body_size 512M;
        proxy_pass http://gitea:3000;
        include /etc/nginx/snippets/proxy-common.conf;
    }
}
