server {
    listen 80;
    server_name ntfy.alex-ashworth.com;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name ntfy.alex-ashworth.com;
    ssl_certificate /etc/letsencrypt/live/ntfy.alex-ashworth.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ntfy.alex-ashworth.com/privkey.pem;
    include /etc/nginx/snippets/ssl-params.conf;
    include /etc/nginx/snippets/tailscale-docker-only.conf;

    location / {
        proxy_pass http://ntfy:80;
        include /etc/nginx/snippets/proxy-common.conf;
        include /etc/nginx/snippets/proxy-websocket.conf;
    }
}
